export const QUIZE_LIST_START = 'QUIZE_LIST_START';
export const QUIZE_LIST_SUCCESS = 'QUIZE_LIST_SUCCESS';
export const QUIZE_LIST_ERROR = 'QUIZE_LIST_ERROR';
export const QUIZE_LIST_DELETE_BY_ID = 'QUIZE_LIST_DELETE_BY_ID';

export const QUIZE_START = 'QUIZE_START';
export const QUIZE_SUCCESS = 'QUIZE_SUCCESS';
export const QUIZE_ERROR = 'QUIZE_ERROR';
export const QUIZE_RETRY = 'QUIZE_RETRY';
export const QUIZE_FINISH = 'QUIZE_FINISH';
export const QUIZE_SET_ANSWER = 'QUIZE_SET_ANSWER';
export const QUIZE_NEXT_ACTIVE_QUESTION = 'QUIZE_NEXT_ACTIVE_QUESTION';

export const QUIZE_CREATOR_ERROR = 'QUIZE_CREATOR_ERROR';
export const QUIZE_CREATOR_RESET = 'QUIZE_CREATOR_RESET';
export const QUIZE_CREATOR_ADD_QUESTION = 'QUIZE_CREATOR_ADD_QUESTION';

export const QUIZE_AUTH = 'QUIZE_AUTH';
export const QUIZE_AUTH_START = 'QUIZE_AUTH_START';
export const QUIZE_AUTH_SUCCESS = 'QUIZE_AUTH_SUCCESS';
export const QUIZE_AUTH_ERROR = 'QUIZE_AUTH_ERROR';
export const QUIZE_AUTH_LOGOUT = 'QUIZE_AUTH_LOGOUT';