export const QUIZE_LIST_START = 'QUIZE_LIST_START';
export const QUIZE_LIST_SUCCESS = 'QUIZE_LIST_SUCCESS';
export const QUIZE_LIST_ERROR = 'QUIZE_LIST_ERROR';

export const QUIZE_START = 'QUIZE_START';
export const QUIZE_SUCCESS = 'QUIZE_SUCCESS';
export const QUIZE_ERROR = 'QUIZE_ERROR';
export const QUIZE_RETRY = 'QUIZE_RETRY';
export const QUIZE_FINISH = 'QUIZE_FINISH';
export const QUIZE_SET_ANSWER = 'QUIZE_SET_ANSWER';
export const QUIZE_NEXT_ACTIVE_QUESTION = 'QUIZE_NEXT_ACTIVE_QUESTION';